apiVersion: v1
kind: Service
metadata:
  name: exporter-managed-server-2
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30317
    port: 8001
    targetPort: 8001
  selector:
    weblogic.createdByOperator: "true"
    weblogic.domainUID: domain1
    weblogic.serverName: managed-server-2
