{
 "title": "WebLogic Server Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domainName",
    "label": "Domain",
    "query": "label_values(weblogic_domainUID)"
   },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": "label_values(weblogic_clusterName)"
   },
   {
    "name": "serverName",
    "label": "Server",
    "query": "label_values(wls_jvm_uptime,weblogic_serverName)"
   },
   {
    "name": "datasource",
    "query": "label_values(wls_datasource_curr_capacity,name)"
   },
   { "name": "test_metrics", "query": "metrics(wls_jms*)" },
   {
    "name": "test_query_result",
    "query": "query_result(topk(1, server_admin_server_listen_port))"
   }
  ]
 },
 "panels": [
  {
   "title": "test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "table test",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_session_pools_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_destinations_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
      },
      {
       "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
      }
     ]
    },
    {
     "title": "Server Uptime",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(wls_jvm_uptime{weblogic_domainUID=\"$domainName\",weblogic_clusterName=\"$clusterName\"}) by (weblogic_serverName)"
      }
     ]
    },
    {
     "title": "Connection Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 7, "x": 6, "y": 16 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"} / (wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"} + wls_datasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})) * 100"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "wls_jvm_heap_free_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
       "legendFormat": " Heap Free  ({{weblogic_serverName}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(wls_datasource_leaked_connection_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (weblogic_serverName,name)"
      },
      {
       "expr": "sum(wls_datasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (weblogic_serverName,name)"
      },
      {
       "expr": "sum(wls_datasource_failed_reserve_request_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (weblogic_serverName,name)"
      },
      {
       "expr": "sum(wls_datasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (weblogic_serverName,name)"
      },
      {
       "expr": "(wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"} / (wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"} + wls_datasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})) * 100"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": " {{name}} @ {{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "Pending Connection Requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wls_datasource_waiting_for_connection_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": " {{name}} @ {{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "Average Connection Delay Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "wls_datasource_connection_delay_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": " {{name}} @ {{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "Connection Rate (per 5m)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(wls_datasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}[5m])",
       "legendFormat": " {{name}} @ {{weblogic_serverName}}"
      }
     ]
    }
   ]
  },
  { "title": "JMS Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_session_pools_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_destinations_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (jmsserver)"
    }
   ]
  },
  {
   "title": "Session Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_jms_session_pools_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "wls_jms_messages_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
     "legendFormat": "Current ({{jmsserver}})"
    },
    {
     "expr": "wls_jms_messages_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
     "legendFormat": "Pending ({{jmsserver}})"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "wls_jms_bytes_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
     "legendFormat": "Current ({{jmsserver}})"
    },
    {
     "expr": "wls_jms_bytes_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
     "legendFormat": "Pending ({{jmsserver}})"
    }
   ]
  },
  {
   "title": "Message Rate (per 5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "irate(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Bytes Rate (per 5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "irate(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Destinations Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(wls_jms_dest_consumers_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_messages_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_messages_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_bytes_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_bytes_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (destination)"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Servers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(count (wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (name))",
       "legendFormat": "{{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "Server Name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
     "repeat": "serverName",
     "format": "percent",
     "valueName": "current",
     "targets": [
      { "expr": "wls_server_activation_time" }
     ]
    },
    {
     "title": "Server Status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
     "repeat": "serverName",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "wls_server_state_val{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 4 },
     "repeat": "serverName",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - wls_jvm_heap_free_percent{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Running Time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
     "repeat": "serverName",
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Open Sockets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "repeat": "serverName",
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "wls_server_open_sockets_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Deployed Applications",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(count(wls_webapp_config_deployment_state{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (app))"
      }
     ]
    },
    {
     "title": "Server Name",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      { "expr": "wls_server_activation_time" }
     ]
    },
    {
     "title": "Server Status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "wls_server_state_val{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - wls_jvm_heap_free_percent{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Running Time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 17, "y": 7 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "Open Sockets",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "wls_server_open_sockets_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "wls_jvm_heap_free_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": " Heap Free  ({{weblogic_serverName}})"
      },
      {
       "expr": "wls_jvm_heap_size_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": "Heap Size ({{weblogic_serverName}})"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "wls_jvm_process_cpu_load{weblogic_domainUID=~\"$domainName\", weblogic_clusterName=~\"$clusterName\"} * 100",
       "legendFormat": " {{weblogic_serverName}}"
      }
     ]
    },
    {
     "title": "Thread Pool",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wls_threadpool_execute_thread_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": "Total Threads ({{weblogic_serverName}})"
      },
      {
       "expr": "wls_threadpool_stuck_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}",
       "legendFormat": "Stuck Threads ({{weblogic_serverName}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Web Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Webapp Execution Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,wls_servlet_execution_time_average{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})",
       "legendFormat": "Average ({{name}})"
      },
      {
       "expr": "topk(5,wls_servlet_execution_time_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})",
       "legendFormat": "Total ({{name}})"
      },
      {
       "expr": "topk(5,wls_servlet_execution_time_high{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})",
       "legendFormat": "High ({{name}})"
      }
     ]
    },
    {
     "title": "Top 5 Webapp Load",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Open Sessions" }
     ],
     "targets": [
      {
       "expr": "topk(5,wls_webapp_config_open_sessions_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})",
       "legendFormat": "Current ({{name}})"
      },
      {
       "expr": "topk(5,wls_webapp_config_sessions_opened_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})",
       "legendFormat": "Total ({{name}})"
      }
     ]
    }
   ]
  }
 ]
}